name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: prod
    permissions:
      contents: write
    steps:
      - name: languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.languages.svg
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14
          plugin_languages_threshold: 2%
      - name: Followers
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.people.followers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_people: yes
          plugin_people_types: followers
      - name: Recently played games
        uses: lowlighter/metrics@latest
        with:
            filename: metrics.plugin.steam.svg
            token: NOT_NEEDED
            base: ""
            plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
            plugin_steam: yes
            plugin_steam_user: "76561198186523489"
            plugin_steam_achievements_limit: 0
      - name: News from hackernews
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.rss.svg
          token: NOT_NEEDED
          base: ""
          plugin_rss: yes
          plugin_rss_source: https://74k1.sh/rss.xml
          plugin_rss_limit: 4
      - name: Spotify - Random track from playlist
        uses: lowlighter/metrics@latest
        with:
            filename: metrics.plugin.music.playlist.spotify.svg
            token: NOT_NEEDED
            base: ""
            plugin_music: yes
            plugin_music_playlist: https://open.spotify.com/embed/playlist/3XOMpKEXs0uMbIQalfNadC
      - name: Last.fm  - Recently listed
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.music.lastfm.recents.svg
          token: NOT_NEEDED
          base: ""
          plugin_music_token: ${{ secrets.LASTFM_KEY }}
          plugin_music: yes
          plugin_music_provider: lastfm
          plugin_music_user: its74k1



